# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-amd64-snap:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: sudo apt update; sudo apt upgrade -y
      - run: sudo apt install -y snapd
      - run: sudo snap install --classic snapcraft
      - run: sudo snapcraft --destructive-mode
      - run:
          name: Upload snap package
          command: |
            sudo mkdir /tmp/artifacts
            sudo cp *.snap /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
  build-arm64-snap:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: sudo apt update; sudo apt upgrade -y
      - run: sudo apt install -y snapd
      - run: sudo snap install --classic snapcraft
      - run: sudo snapcraft --destructive-mode
      - run:
          name: Upload snap package
          command: |
            sudo mkdir /tmp/artifacts
            sudo cp *.snap /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-amd64-snap
      - build-arm64-snap
